from .admin_auth import admin_blueprint
from .auth import auth_blueprint
from .global_alloys import alloys_blueprint
from .last_simulation import last_sim_blueprint
from .ratings import ratings_blueprint
from .save_simulation import save_sim_blueprint
from .share import share_blueprint
from .sim_alloys import sim_alloys_blueprint
from .sim_configurations import configs_blueprint
from .simulation import sim_blueprint
from .user_alloys import user_alloys_blueprint
from .users import users_blueprint
from .root import root_blueprint
from .data_personalisation import data_personal_blueprint
