image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - apk add --no-cache --quiet py-pip bash
          - apk add --quiet python python-dev build-base libffi-dev openssl-dev libgcc
          - pip install --no-cache-dir docker-compose==1.24.0
          - docker-compose -v
          - docker-compose up -d
          - docker-compose down
          - python -m unittests services/server/tests/test_simulation