image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - pip
          - pip3
          - docker
        script:
          - apk add --quiet py3-pip bash python3 python3-dev
          - apk add --quiet build-base libffi-dev openssl-dev libgcc
          - python --version
          - pip -V
          - pip3 -V
          - pip3 install --cache-dir ~/.pip3/cache/ -q -r ./services/server/requirements.txt
          - export PYTHONPATH=$PYTHONPATH:./services/server/:./services/server/simulation/
          - cd ./services/server
          #          - python -m unittest ./services/server/tests/test_simulation.py  # Run specific Phase Simulation tests only
          - python3 -m unittest tests/test_simulation.py  # Run specific Phase Simulation tests only
          - pip3 install --no-cache-dir docker-compose==1.24.0
          - docker-compose -v
          - cd ../../
          - docker-compose up -d --build
          - docker-compose exec server python manage.py test  # This should start the test runner for the API server
          - docker-compose down
definitions:
  caches:
    pip3: ~/.pip3/cache