image: docker:stable

options:
  docker: true

pipelines:
  branches:
    develop:
      - step:
          services:
            - docker
          caches:
            - pip3
            - docker
            - node
            - pip
          script:
            - apk add --quiet py3-pip bash python3 python3-dev
            - apk add --quiet build-base libffi-dev openssl-dev libgcc
            - pip3 install --quiet --cache-dir ~/.pip3/cache --upgrade pip
            - cd ./arclytics.io
            - git checkout develop
            - cd ../
            - pip3 install --quiet --cache-dir ~/.pip3/cache docker-compose==1.24.1
            - docker-compose -v
            - docker-compose -p arc -f docker-compose-gke.yaml up -d --build simcct celery-worker redis nginx mongodb client
            #- docker exec -t arc_simcct_1 python manage.py test
            - docker-compose -p arc down

definitions:
  caches:
    pip3: ~/.pip3/cache
