image: docker:stable

options:
  docker: true

pipelines:
  branches:
    develop:
      - step:
          services:
            - docker
          caches:
            - pip3
            - docker
          script:
            - mkdir -p ~/.pip3/cache
            - apk add --quiet py3-pip bash python3 python3-dev
            - apk add --quiet build-base libffi-dev openssl-dev libgcc
            - python3 --version
            - pip3 install --quiet --cache-dir ~/.pip3/cache --upgrade pip
            - pip3 -V
            - pip3 install --quiet --cache-dir ~/.pip3/cache -r ./services/user-server/requirements.txt
            - export PYTHONPATH=$PYTHONPATH:./services/server/:./services/user-server/simulation/
            - cd ./services/simulation-server
            - python3 -m unittest tests/test_simulation.py  # Run specific Phase Simulation tests only
            - cd ../../
            - pip3 install --quiet --cache-dir ~/.pip3/cache docker-compose==1.24.0
            - docker-compose -v
            - docker-compose up -d --build
            - docker-compose exec -T server python manage.py test  # This should start the test runner for the API server
            - docker-compose down

definitions:
  caches:
    pip3: ~/.pip3/cache