image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - apk add --no-cache --quiet py-pip bash
          - apk add --quiet build-base libffi-dev openssl-dev libgcc
          - apk add --quiet python3 python3-dev
          - pip3 install -r ./services/server/requirements.txt
          - python3 -m unittest discover -s ./services/server/tests -t ./services/server
          - pip3 install --no-cache-dir docker-compose==1.24.0
          - docker-compose -v
          - docker-compose up -d --build
          - docker-compose exec server python manage.py test  # This should start the test runner for the API server
          - docker-compose down
