image: docker:stable

options:
  docker: true

pipelines:
  branches:
    feature/ARC-55_api:
      - step:
          services:
            - docker
          caches:
            - pip3
            - docker
            - node
            - pip
          script:
            - apk add --quiet py3-pip bash python3 python3-dev
            - apk add --quiet build-base libffi-dev openssl-dev libgcc
            - pip3 install --quiet --cache-dir ~/.pip3/cache --upgrade pip
            - pip3 install --quiet --cache-dir ~/.pip3/cache docker-compose==1.24.0
            - docker-compose -v
            - docker-compose up -d --build simcct users-server redis mongodb client
            # This should start the test runner for the API server
            - ./run_tests.sh -c -t server
            - docker-compose down

definitions:
  caches:
    pip3: ~/.pip3/cache
