
version: '3.7'

services:

  arclytics:
    build:
      context: ./services/arclytics
      dockerfile: Dockerfile-prod
      labels:
        arclytics.io: "production"
    image: gcr.io/arclytics-sim/arc_sim_flask_service:1.0.0
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - FLASK_APP=arc_app/app.py
      - FLASK_ENV=production
      - APP_SETTINGS=configs.flask_conf.ProductionConfig
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_APP_DB=${MONGO_APP_DB}
      - MONGO_APP_USER=${MONGO_APP_USER}
      - MONGO_APP_USER_PASSWORD=${MONGO_APP_USER_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SIMCCT_HOST=simcct:8001
      - CLIENT_HOST=client:80
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    depends_on:
      - mongodb
      - redis
    networks:
      - host

  simcct:
    build:
      context: ./services/simcct
      dockerfile: Dockerfile-prod
      labels:
        arclytics.io: "production"
    image: gcr.io/arclytics-sim/arc_sim_service:1.3.0
    ports:
      - 8001:8001
    expose:
      - 8001
    environment:
      - FLASK_APP=sim_app/app.py
      - FLASK_ENV=production
      - APP_SETTINGS=configs.flask_conf.ProductionConfig
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_APP_DB=${MONGO_APP_DB}
      - MONGO_APP_USER=${MONGO_APP_USER}
      - MONGO_APP_USER_PASSWORD=${MONGO_APP_USER_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - USERS_HOST=arclytics:8000
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    depends_on:
      - mongodb
      - redis
    networks:
      - host

  redis:
    build:
      context: ./services/redis
      dockerfile: Dockerfile
      labels:
        arclytics.io: "production"
    image: gcr.io/arclytics-sim/arc_sim_redis:1.1.0
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - host

  mongodb:
    build:
      context: ./services/db
      dockerfile: Dockerfile-prod
      labels:
        arclytics.io: "production"
    image: gcr.io/arclytics-sim/arc_sim_mongo:1.1.0
    restart: always
    volumes:
      - mongo-volume-mount:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_APP_DB=${MONGO_APP_DB}
      - MONGO_APP_USER=${MONGO_APP_USER}
      - MONGO_APP_USER_PASSWORD=${MONGO_APP_USER_PASSWORD}
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - host

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      labels:
        arclytics.io: "production"
    image: gcr.io/arclytics-sim/arc_sim_client:1.1.0
    ports:
      - 80:80
    expose:
      - 80
    environment:
      - NODE_ENV=production
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - ARCLYTICS_SERVICE_HOST=${ARCLYTICS_SERVICE_HOST}
      - ARCLYTICS_SERVICE_PORT=${ARCLYTICS_SERVICE_PORT}
    depends_on:
      - arclytics
      - mongodb
    networks:
      - host

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - arclytics
      - simcct

networks:
  host:
    driver: bridge
    labels:
      arclytics.io: "production"

# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  mongo-volume-mount:
    labels:
      arclytics.io: "production"
