
version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    image: arclytics/arc_sim_users_service:1.0
    volumes:  # used to mount the code into the container for live updates
      - ./services/users:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=configs.flask_conf.ProductionConfig
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SIMCCT_HOST=simcct:8001
      - CLIENT_HOST=client:3000
    depends_on:
      - mongodb
      - redis
      - celery-worker
    networks:
      - host

  celery-worker:
    build:
      context: ./services/celery-worker
      dockerfile: Dockerfile
    image: neuraldev/arc_sim_celery_service:1.0
    volumes:
      - ./services/celery-worker:/usr/src/app
    ports:
      - 5555:5555  # Flower Web GUI management of Celery
    expose:
      - 5555
    environment:
      - C_FORCE_ROOT=true
      - FLASK_ENV=production
      - APP_SETTINGS=flask_conf.ProductionConfig
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - host

  simcct:
    build:
      context: ./services/simcct
      dockerfile: Dockerfile-prod
    image: arclytics/arc_simcct_service:1.3
    volumes:
      - ./services/simcct:/usr/src/app
    ports:
      - 8001:8001
    expose:
      - 8001
    environment:
      - FLASK_APP=sim_app/app.py
      - FLASK_ENV=production
      - APP_SETTINGS=configs.flask_conf.ProductionConfig
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USERS_HOST=users:8000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongodb:27017
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    depends_on:
      - redis
    networks:
      - host

  redis:
    build:
      context: ./services/redis
      dockerfile: Dockerfile
    image: arclytics/arc_sim_redis:1.1
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - host

  mongodb:
    build:
      context: ./services/db
      dockerfile: Dockerfile-prod
    image: arclytics/arc_sim_mongo:1.1
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - host

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
    image: arclytics/arc_sim_client:1.1
    volumes:
      - ./services/client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - users
      - mongodb
    links:
      - users
      - simcct
    networks:
      - host

networks:
  host:
