name: arclytics_api
channels:
  - anaconda
  - conda-forge
  - nodefaults
dependencies:
  - django=2.1.7
  - djangorestframework=3.9.2
  - numpy=1.16.2
  - psycopg2=2.7.6.1
  - python=3.7.2
  - sqlite=3.27.2
  - vc=14.1
  - vs2015_runtime=15.5.2

