export const GET_USERS = 'users/GET_USERS'
export const CREATE_USER = 'users/CREATE_USER'
export const UPDATE_USER = 'users/UPDATE_USER'
export const DEACTIVATE_USER = 'users/DEACTIVATE_USER'
export const PROMOTE_ADMIN = 'users/PROMOTE_ADMIN'
export const ENABLE_USER = 'users/ENABLE_USER'
