export const GET_USERS = 'users/GET_USERS'
export const SEARCH_USERS = 'users/SEARCH_USERS'
export const DEACTIVATE_USER = 'users/DEACTIVATE_USER'
export const PROMOTE_ADMIN = 'users/PROMOTE_ADMIN'
export const ENABLE_USER = 'users/ENABLE_USER'
