export const UPDATE_CONFIG_METHOD = 'sim/UPDATE_CONFIG_METHOD'
export const UPDATE_CONFIG = 'sim/UPDATE_CONFIG'
export const UPDATE_DISPLAY_USER_CURVE = 'sim/UPDATE_DISPLAY_USER_CURVE'

export const INIT_SESSION = 'sim/INIT_SESSION'
export const UPDATE_ALLOY_OPTION = 'sim/UPDATE_ALLOY_OPTION'
export const UPDATE_COMP = 'sim/UPDATE_COMP'
export const UPDATE_DILUTION = 'sim/UPDATE_DILUTION'
export const RUN_SIM = 'sim/RUN_SIM'

export const UPDATE_CCT_INDEX = 'sim/UPDATE_CCT_INDEX'
export const LOAD_SIM = 'sim/LOAD_SIM'
export const LOAD_SIM_FROM_FILE = 'sim/LOAD_SIM_FROM_FILE'
export const LOAD_PERSISTED_SIM = 'sim/LOAD_PERSISTED_SIM'
export const LOAD_LAST_SIM = 'sim/LOAD_LAST_SIM'
export const LOAD_SIM_FROM_TIME_MACHINE = 'sim/LOAD_SIM_FROM_TIME_MACHINE'

export const RESET_SIM = 'sim/RESET_SIM'
