apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-INST
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: pd-ssd-disk-INST  # Make sure you use the SSD name created in `gcloud`
