apiVersion: v1
kind: Service
metadata:
  name: simcct-service
  labels:
    app: simcct
spec:
  type: LoadBalancer
  loadBalancerIP: 35.189.61.10
  selector:
    app: simcct
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simcct
  labels:
    app: simcct
spec:
  selector:
    matchLabels:
      app: simcct
  replicas: 1
  template:
    metadata:
      labels:
        app: simcct
        replicaset: SimRepSet
    spec:
      containers:
      - name: simcct-container
        image: asia.gcr.io/arc-sim-testing/arc_sim_service:1.1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthy
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 15
          successThreshold: 2
          failureThreshold: 5
        resources:
          requests:
            cpu: 750m
            memory: 2Gi
        env:
        - name: FLASK_APP
          value: "sim_api/app.py"
        - name: FLASK_ENV
          value: "production"
        - name: APP_SETTINGS
          value: "configs.flask_conf.ProductionConfig"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: secret_key
        - name: SECURITY_PASSWORD_SALT
          valueFrom:
            secretKeyRef:
              name: credentials
              key: security_password_salt
        - name: MONGO_HOST
          value: "mongo-0.mongo-service.default.svc.cluster.local"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_APP_DB
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mongo_app_db
        - name: MONGO_APP_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mongo_app_user
        - name: MONGO_APP_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mongo_app_user_password
        - name: REDIS_HOST
          value: "redis-service.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: redis_password
        - name: CLIENT_PROTOCOL
          value: "https"
        - name: CLIENT_HOST
          value: "app.arclytics.io"
        - name: CLIENT_PORT
          value: "443"
        - name: DASK_SCHEDULER_ADDRESS
          value: "tcp://dask-scheduler:8786"
