export const GET_GLOBAL_ALLOYS = 'alloys/GET_GLOBAL_ALLOYS'
export const CREATE_GLOBAL_ALLOY = 'alloys/CREATE_GLOBAL_ALLOY'
export const UPDATE_GLOBAL_ALLOY = 'alloys/UPDATE_GLOBAL_ALLOY'
export const DELETE_GLOBAL_ALLOY = 'alloys/DELETE_GLOBAL_ALLOY'

export const GET_USER_ALLOYS = 'alloys/GET_USER_ALLOYS'
export const CREATE_USER_ALLOY = 'alloys/CREATE_USER_ALLOY'
export const UPDATE_USER_ALLOY = 'alloys/UPDATE_USER_ALLOY'
export const DELETE_USER_ALLOY = 'alloys/DELETE_USER_ALLOY'
