openapi: 3.0.2
info:
  version: 0.0.2
  title: Arclytics Sim API
  description: Swagger spec for documenting the users and simulation service
servers:
  - description: Users Service Flask Server
    url: 'http://localhost'
  - description: SimCCT Service Flask Server
    url: 'http://localhost'
paths:
  /ping:
    get:
      summary: Just a sanity check
      responses:
        '200':
          description: Successful sanity checking.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of `success` or `fail`.
                  message:
                    type: string
                    description: The message response
              example:
                status: success
                message: pong!
  # TODO:
  /users:
    get:
      summary: Returns all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: user object

  '/users/{id}':
    get:
      summary: Returns a user based on a single user ID
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          schema:
            type: string
            format: ObjectId
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          description: The request parameters are bad.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    format: string
                    example: fail
                  message:
                    type: string
                    format: string
                    example: Provide a valid JWT auth token.
        '401':
          description: The user is not authorized to perform this request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    format: string
                  message:
                    type: string
                    format: string
              examples:
                SignedOut:
                  value:
                    status: fail
                    message: User must sign in again.

  # TODO:
  /auth/register:
    post:
      summary: Register and create a new user
      requestBody:
        description: User details to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                user_type:
                  type: int
                  format: string
              required:
                - email
                - password
      responses:
        '200':
          description: user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  #TODO:
  /auth/login:
    post:
      summary: Logs a user in
      requestBody:
        description: User to log in
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            example:
              email: tony@avengers.io
              password: IAmIronMan
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT Token
                  message:
                    type: string
                    description: The message response
              example:
                token: lkj12309isdfjl1j23lkjsdlkfkjhsdfsdf
                message: Successfully logged in.
  /auth/status:
    get:
      summary: Returns the logged in user's status
      security:
        - bearerAuth: []
      responses:
        '200':
          description: api.models.User object
  /auth/logout:
    get:
      summary: Logs a user out
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully logged out
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    user:
      properties:
        email:
          type: string
          required: true
          uniqueItems: true
        password:
          type: string
          required: true
          minLength: 6
          maxLength: 255
          uniqueItems: true
        first_name:
          type: string
          required: true
          maxLength: 255
        last_name:
          type: string
          required: true
          maxLength: 255
        username:
          type: string
          required: true
          minLength: 1
          maxLength: 180
        user_type:
          type: string
          format: tuple
          required: false
          maxLength: 1
          example: '2'
          default: '2'
