apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arclytics
  labels:
    name: arclytics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: arclytics
    spec:
      containers:
      - name: users
        image: arclytics/arc_sim_flask_service:1.0
        imagePullPolicy: Never
        env:
        - name: FLASK_APP
          value: "arc_app/app.py"
        - name: FLASK_ENV
          value: "production"
        - name: APP_SETTINGS
          value: "configs.flask_conf.ProductionConfig"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: secret_key
        - name: SECURITY_PASSWORD_SALT
            valueFrom:
              secretKeyRef:
                name: credentials
                key: security_password_salt
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONOGO_APP_DB
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mongo_app_db
        - name: MONGO_APP_USER
            valueFrom:
              secretKeyRef:
                name: credentials
                key: app_user
        - name: MONGO_APP_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: app_user_password
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: redis_password
        - name: MAIL_SERVER
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mail_server
        - name: MAIL_PORT
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mail_port
        - name: MAIL_USE_TLS
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mail_use_tls
        - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mail_username
        - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mail_password
        - name: SIMCCT_HOST
          value: "simcct:8001"
        - name: CLIENT_HOST
          value: "client:80"
        - name: DASK_SCHEDULER_ADDRESS
          value: "tcp://dask-scheduler:8786"
      restartPolicy: Always
