apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
         app: celery
    spec:
      containers:
      - name: celery-worker
        image: gcr.io/arclytics-sim/arc_sim_celery:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 5555
        env:
        - name: FLASK_ENV
          value: "production"
        - name: APP_SETTINGS
          value: "flask_conf.ProductionConfig"
        - name: REDIS_HOST
          value: "redis-service.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: redis_password
        - name: MAIL_SERVER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mail_server
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mail_username
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mail_password
      initContainers:
        - name: init-celery-broker
          image: busybox
          command: ['sh', '-c', 'until nslookup redis-service; do echo waiting for redis-service to be available; sleep 2; done;']
