apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-worker
  namespace: arclytics
  labels:
    app: celery-worker
    component: celery-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
         app: celery
         component: celery-worker
    spec:
      initContainers:
        - name: init-celery-broker
          image: busybox
          command: ['sh', '-c', 'until nslookup redis-service; do echo waiting for redis-service to be available; sleep 2; done;']
      containers:
        - name: celery-worker-container
          image: gcr.io/arclytics/arc_sim_celery:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
          resources:
            requests:
              cpu: 750m
              memory: 2Gi
            limits:
              cpu: 1250m
              memory: 2Gi
          readinessProbe:
            exec:
              command:
                - cat
                - /usr/src/app/healthy
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 15
            successThreshold: 2
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - cat
                - /usr/src/app/healthy
            initialDelaySeconds: 5
            periodSeconds: 60
          env:
            - name: FLASK_ENV
              value: "production"
            - name: APP_SETTINGS
              value: "flask_conf.ProductionConfig"
            - name: REDIS_HOST
              value: "redis-service.arclytics.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: redis_password
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mail_server
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mail_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mail_password
            - name: ELASTIC_APM_SERVER_URL
              value: http://apm-service.arclytics.svc.cluster.local:8200
              #value: https://apm.arclytics.io
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: elastic_apm_secret_token
            - name: MONGO_HOST
              value: "mongo-0.mongo-service.arclytics.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_APP_DB
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongo_app_db
            - name: MONGO_APP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongo_app_user
            - name: MONGO_APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongo_app_user_password
