apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-secure-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: arc-ip
spec:
  tls:
    - secretName: client-https-secret
  rules:
  - host: app.arclytics.io
    http:
      paths:
      - backend:
          serviceName: client-service
          servicePort: 8080
