apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-https
spec:
  type: LoadBalancer
  loadBalancerIP: 35.197.160.183
  selector:
    app: client-https
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-https
  labels:
    app: client-https
spec:
  selector:
    matchLabels:
      app: client-https
  replicas: 1
  template:
    metadata:
      labels:
        app: client-https
        environment: production
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: client-https-secret
      containers:
      - name: client-https-container
        image: gcr.io/arclytics-sim/arc_sim_client:1.1.3
        ports:
        - containerPort: 8080
        - containerPort: 443
        env:
          - name: REACT_APP_SIM_HOST
            value: "api.arclytics.io"
          - name: REACT_APP_SIM_PORT
            value: "80"
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
