apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
        environment: production
    spec:
      containers:
      - name: client
        image: gcr.io/arclytics-sim/arc_sim_client:1.1.2
        ports:
        - containerPort: 8080
        env:
          - name: NODE_ENV
            value: "production"
          - name: REACT_APP_SIM_HOST
            value: "app.arclytics.io"
          - name: REACT_APP_SIM_PORT
            value: "80"
