apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
        environment: production
    spec:
      containers:
      - name: client
        image: arclytics/arc_sim_client:1.1
        imagePullPolicy: Always  # Never -- use for local
        ports:
        - containerPort: 80
