apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
