apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: arc-ip
spec:
  backend:  # Default backend
    serviceName: client-service
    servicePort: 8080
