apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: arclytics
  labels:
    app: client-https
    component: client
spec:
  type: NodePort
  selector:
    app: client-https
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-https
  namespace: arclytics
  labels:
    app: client-https
    component: client
spec:
  selector:
    matchLabels:
      app: client-https
  replicas: 2
  template:
    metadata:
      labels:
        app: client-https
        component: client
    spec:
      containers:
      - name: client-https-container
        image: asia.gcr.io/arc-sim-testing/arc_sim_client:1.2.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthy
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 15
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
              - cat
              - /etc/nginx/healthy
          initialDelaySeconds: 15
          periodSeconds: 120
