apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-https
spec:
  type: NodePort
  selector:
    app: client-https
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-https
  labels:
    app: client-https
    replicaset: ClientRepSet
spec:
  selector:
    matchLabels:
      app: client-https
  replicas: 2
  template:
    metadata:
      labels:
        app: client-https
        environment: production
    spec:
      containers:
      - name: client-https-container
        image: asia.gcr.io/arc-sim/arc_sim_client:1.1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_SIM_HOST
            value: "https://api.arclytics.io"
          - name: REACT_APP_SIM_PORT
            value: "8000"
