apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: kube-system
type: Opaque
data:
  secret_key: ZDhjOGYwY2IzMmVkYjkxNDYxNDIwMGQwN2RlOTYwNTI2MmFkNjkwMWZkZGE2NTdmNWU3YjA4MThiMDcxODZhOWVhNmVlZmVmY2YwNGVjMzg3MGQzM2RkY2YzM2Y1MDVhNzM0ODg4MzczMmUzZThmNjY1YzllNzM2NzcyYzViZGQ=
  secret_token: NGJjMmE3ODM5NDEyZWNkMTU0YjI1YzdmZjI4ZjBkZDE3MTI3NDFjODk3ZDdjMDg4ZDU5OGJmOTc2MGRlZmJkMTBlYjAzZTMwZTA2NWU1YzczMmMxODFmY2I0MDk1ZmJiN2IxY2Q0OWUwYjk1Yzk4MGEyYTNmN2NjODBlZGFlZGU=
  elastic_user: ZWxhc3RpYw==
  elastic_password: Kyp6ZTkkLEpNPns7ejlKM1g=
