apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  namespace: arclytics
  labels:
    app: apm-server
    component: apm-server
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      frontend:
        enabled: false
    setup.template.settings:
      index:
        number_of_shards: 1
        codec: best_compression
    setup.kibana:
      enabled: true
      host: http://kibana-service.arclytics.svc.cluster.local:5601
    output.elasticsearch:
      hosts: ["http://elasticsearch-0.elasticsearch.arclytics.svc.cluster.local:9200", "http://elasticsearch-1.elasticsearch.arclytics.svc.cluster.local:9200", "http://elasticsearch-2.elasticsearch.arclytics.svc.cluster.local:9200"]
---
apiVersion: v1
kind: Service
metadata:
  name: apm-service
  namespace: arclytics
  labels:
    app: apm-server
    component: apm-server
spec:
  type: NodePort
  selector:
    app: apm-server
  ports:
    - name: http
      port: 8200
      targetPort: 8200
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apm-server
  namespace: arclytics
  labels:
    app: apm-server
    component: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
        component: apm-server
    spec:
      containers:
        - name: apm-server-container
          image: docker.elastic.co/apm/apm-server:7.3.2
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch.arclytics.svc.cluster.local
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: KIBANA_HOST
              value: kibana-service.arclytics.svc.cluster.local
            - name: KIBANA_PORT
              value: "5601"
          volumeMounts:
            - name: apm-server-config
              mountPath: /usr/share/apm-server/apm-server.yml
              readOnly: true
              subPath: apm-server.yml
      volumes:
        - name: apm-server-config
          configMap:
            name: apm-server-config
