apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: arclytics
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.port: 5601
    server.name: "Arclytics Sim"
    elasticsearch.hosts: ["elasticsearch-0.elasticsearch.arclytics.svc.cluster.local", "elasticsearch-1.elasticsearch.arclytics.svc.cluster.local", "elasticsearch-2.elasticsearch.arclytics.svc.cluster.local" ]
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: arclytics
  labels:
    app: kibana
    component: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: arclytics
  labels:
    app: kibana
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.3.2
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
        ports:
          - name: http
            protocol: TCP
            containerPort: 5601
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: XPACK_SECURITY_ENABLED
            value: "false"
        volumeMounts:
          - name: kibana-config
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
