kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: inter-node
      port: 9300
      protocol: TCP
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-container
          image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: cluster.name
              value: arc-sim-aust
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # Will resolve to elasticsearch-[0,1,2]
            - name: discovery.seed_hosts
              value: 'elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch'
            - name: cluster.initial_master_nodes
              value: 'elasticsearch-0,elasticsearch-1,elasticsearch-2'
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'  # JVM to use a minimum and maximum heap size of 512 MB.
          volumeMounts:
            - name: elasticsearch-pvc
              mountPath: /usr/share/elasticsearch/data
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-pvc
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ['sh', '-c', 'ulimit -n 65536']
          securityContext:
            privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-pvc
      labels:
        app: elasticsearch
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ 'ReadWriteOnce' ]
      resources:
        requests:
          storage: 100Gi
