apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-INST
  namespace: arclytics
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: es-standard-disk-INST  # Make sure you use the SSD name created in `gcloud`
