apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: arclytics
  labels:
    app: fluentd
    service: fluentd-logging
data:
  fluent.conf: |
    <match fluent.**>
        # this tells fluentd to not output its log on stdout
        @type null
    </match>
    # here we read the logs from Docker's containers and parse them
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    # we use kubernetes metadata plugin to add metadata to the log
    <filter kubernetes.**>
        @type kubernetes_metadata
    </filter>
    # we send the logs to Elasticsearch
    <match kubernetes.**>
        @type elasticsearch
        include_tag_key true
        host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
        port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
        scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
        ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
        user "#{ENV['FLUENT_ELASTICSEARCH_USER']}" # remove these lines if not needed
        password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}" # remove these lines if not needed
        reload_connections true
        logstash_prefix logstash
        logstash_format true
        <buffer>
            flush_thread_count 8
            flush_interval 5s
            chunk_limit_size 2M
            queue_limit_length 32
            retry_max_interval 30
            retry_forever true
        </buffer>
    </match>
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: arclytics
  labels:
    app: fluentd
    service: fluentd-logging
spec:
  template:
    metadata:
      labels:
        app: fluentd
        service: fluentd-logging
    spec:
      serviceAccount: fluentd      # If RBAC is enabled -- it is: efk-fluentd-gke-rbac.yaml
      serviceAccountName: fluentd  # If RBAC is enabled -- it is: efk-fluentd-gke-rbac.yaml
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: elasticsearch
              # value: "elasticsearch.arclytics.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            # X-Pack Authentication  -- not using
            # =====================
            #- name: FLUENT_ELASTICSEARCH_USER
            #  valueFrom:
            #    secretKeyRef:
            #      name: credentials
            #      key: elastic_user
            #- name: FLUENT_ELASTICSEARCH_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: credentials
            #      key: elastic_password
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            # If we want to configure our own config file, which we are not.
            #- name: fluentd-config
            #  mountPath: /fluetnd/etc  # path of fluentd config file
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # Read comment in volumeMounts.
        #- name: fluentd-config
        #  configMap:
        #    name: fluentd-config
