apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: arc-secure-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "arclytics-ip"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: client-https-secret
  rules:
  - host: app.arclytics.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: client-service
          servicePort: 8080
  - host: api.arclytics.io
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: simcct-service
          servicePort: 8000
