apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: arclytics-ingress
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: client
          servicePort: 80
      - path: /api/v1/arc
        backend:
          serviceName: arclytics
          servicePort: 8000
