apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: arc-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: arc-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: client-service
          servicePort: 80
