apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-INST
  namespace: arclytics
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    fsType: xfs
    pdName: mongo-standard-disk-INST

