apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: arclytics/arc_sim_mongo:1.1
        imagePullPolicy: Never
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mongo_root_user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mongo_root_password
          - name: MONGO_APP_DB
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mongo_app_db
          - name: MONGO_APP_USER
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mongo_app_user
          - name: MONGO_APP_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mongo_app_user_password
        volumeMounts:
          - name: mongo-volume-mount
            mountPath: /data/db
      volumes:
      - name: mongo-volume-mount
        persistentVolumeClaim:
          claimName: mongo-pvc
      restartPolicy: Always
