apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: pd-ssd-disk-2  # Make re you sure you use the SSD name created in `gcloud`
