apiVersion: v1
kind: Service
metadata:
  name: nginx-secure-service
  labels:
    role: nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  selector:
    role: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secure
spec:
  selector:
    matchLabels:
      role: nginx
  replicas: 1
  template:
    metadata:
      labels:
        role: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: nginx-secure-container
        image: bprashanth/nginxhttps:1.0
        ports:
        - containerPort: 443
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
