apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    role: redis
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
  labels:
    name: database
spec:
  serviceName: redis-service
  replicas: 1
  template:
    metadata:
      labels:
        role: redis
        environment: production
    spec:
      containers:
        - name: redis-container
          image: gcr.io/arclytics-sim/arc_sim_redis:1.1.0
          args: ["--requirepass", "$(REDIS_PASSWORD)", "--appendonly", "yes",
                 "--save", "900", "1"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: redis_password
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
        annotations:
          volume.beta.kubernetes.io/storage-class: "fast"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 30Gi
