apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: arclytics
  labels:
    app: redis
    service: redis-persistence
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
  namespace: arclytics
  labels:
    app: redis
    service: redis-persistence
spec:
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        service: redis-persistence
        replicaset: RedisRepSet
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis-container
          image: asia.gcr.io/arc-sim/arc_sim_redis:1.1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 4Gi
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--appendonly"
            - "yes"
            - "--save"
            - "900"
            - "1"
          ports:
            - containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: redis_password
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
        labels:
          app: redis
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
