apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: arclytics
  labels:
    app: redis-cluster
    service: redis-persistence
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis-cluster
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: arclytics
  labels:
    app: redis-cluster
    service: redis-persistence
spec:
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis-cluster
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        service: redis-persistence
        replicaset: RedisRepSet
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis-container
          image: asia.gcr.io/arc-sim/arc_sim_redis:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 4Gi
          command: ["/usr/local/bin/redis-server"]
          args: ["/redis-conf/redis.conf"]
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h $(hostname) ping"
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h $(hostname) ping"
            initialDelaySeconds: 30
            periodSeconds: 15
          ports:
            - containerPort: 6379
              protocol: TCP
              name: client
            - containerPort: 16379
              protocol: TCP
              name: inter-node
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: redis_password
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
        namespace: arclytics
        labels:
          app: redis-cluster
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 30Gi
