apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: mongodb
        image: neuraldev/arc_sim_redis:1.1
        env:
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: user
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: password
        volumeMounts:
          - name: redis-volume-mount
            mountPath: /var/lib/redis/data
      volumes:
      - name: redis-volume-mount
        persistentVolumeClaim:
          claimName: redis-pvc
      restartPolicy: Always
