apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  user: YXJjbHl0aWNz
  password: d2VhcmVudW1iZXJvbmUh
  app_user: YXJjbHl0aWNz
  app_user_password: aWFtaXJvbm1hbg==
