apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simcct
  labels:
    name: simcct
    app: simcct
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simcct
        role: simcct
        environment: production
    spec:
      # Set this: kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ \
      # --docker-username=arclytics \
      # --docker-password=<Docker Password> \
      # --docker-email="andrew@neuraldev.io"
      # Don't forget to escape "!"
      imagePullSecrets:  # Required for private images especially on Docker Hub
        - name: regcred
      containers:
        - name: simcct
          image: arclytics/arc_simcct_service:1.3  # -- use local or Docker Hub build
          env:
            - name: FLASK_APP
              value: "sim_app/app.py"
            - name: FLASK_ENV
              value: "production"
            - name: APP_SETTINGS
              value: "configs.flask_conf.ProductionConfig"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: secret_key
            - name: SECURITY_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: security_password_salt
            - name: MONGO_HOST
              value: "mongo-0.mongo-service.default.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONOGO_APP_DB
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongo_app_db
            - name: MONGO_APP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongo_app_user
            - name: MONGO_APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mongo_app_user_password
            - name: REDIS_HOST
              value: "redis-0.redis-service.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: redis_password
            - name: USER_HOST
              value: "arclytics:8000"
            - name: DASK_SCHEDULER_ADDRESS
              value: "tcp://dask-scheduler:8786"
