apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simcct
  labels:
    name: simcct
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simcct
    spec:
      containers:
      - name: simcct
        image: arclytics/arc_simcct_service:1.3
        imagePullPolicy: Never
        env:
        - name: FLASK_ENV
          value: "production"
        - name: APP_SETTINGS
          value: "configs.flask_conf.ProductionConfig"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SIMCCT_HOST
          value: "simcct:8001"
        - name: CLIENT_HOST
          value: "client:3000"
        - name: DASK_SCHEDULER_ADDRESS
          value: "tcp://dask-scheduler:8786"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
      restartPolicy: Always
