export const RESET_FEEDBACK = 'feedback/RESET_FEEDBACK'
export const CLOSE_FEEDBACK = 'feedback/CLOSE_FEEDBACK'
export const UPDATE_FEEDBACK = 'feedback/UPDATE_FEEDBACK'
export const GET_FEEDBACK = 'feedback/GET_FEEDBACK'
export const SEARCH_FEEDBACK = 'feedback/SEARCH_FEEDBACK'
