# MULTISTAGE BUILD PATTERN

# build environment
FROM node:10.16.2-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
COPY . /app

# Set environment variables at BUILD TIME
ARG REACT_APP_ARC_SERVICE_URL
ENV REACT_APP_ARC_SERVICE_URL $REACT_APP_ARC_SERVICE_URL
ARG REACT_APP_SIM_SERVICE_URL
ENV REACT_APP_SIM_SERVICE_URL $REACT_APP_ARC_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
#ARG REACT_APP_API_GATEWAY_URL
#ENV REACT_APP_API_GATEWAY_URL $REACT_APP_API_GATEWAY_URL

RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]
