FROM continuumio/miniconda3:4.6.14
# note: Using the miniconda base because I want to install numpy with some
# optimisation C-libraries such as openblas which conda does for you
# when you install numpy.

LABEL maintainer="Andrew Che <andrew@neuraldev.io>"

RUN conda install --yes --freeze-installed -q \
    -c anaconda \
    python==3.7.3 \
    python-blosc \
    cytoolz \
    pip \
    nomkl \
    dask==2.3.0 \
    numpy==1.16.4 \
    conda-forge::marshmallow==3.0.1 \
    conda-forge::flask==1.0.2 \
    && conda clean -tipsy \
    && find /opt/conda/ -type f,l -name '*.a' -delete \
    && find /opt/conda/ -type f,l -name '*.pyc' -delete \
    && find /opt/conda/ -type f,l -name '*.js.map' -delete \
    && find /opt/conda/lib/python*/site-packages/bokeh/server/static -type f,l -name '*.js' -not -name '*.min.js' -delete \
    && rm -rf /opt/conda/pkgs

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --quiet --no-cache-dir -r requirements.txt

# add app
COPY . /usr/src/app
RUN rm -rf /usr/src/app/docker-entrypoint.sh

# which conda --> /opt/conda/bin/conda
# which python --> /opt/conda/bin/python

CMD ["gunicorn", "-b 0.0.0.0:8001", "manage:app"]
